server:
  port: 7071
spring:
  application:
    name: msv-wikimedia-consumer
    version: "@project.version@"

  # Postgresql Jdbc
#  datasource:
#    url: jdbc:postgresql://localhost:5433/wikimedia
#    username: develop
#    password: develop123
#    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

  # Postgresql Reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/wikimedia
    username: develop
    password: develop123
  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      bootstrap-servers: ${HOST:localhost}:${PORT:9092}
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # properties:
        # spring.json.trusted.packages: '*'

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    # io.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG